disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Garrett Holland"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Personal site of Garrett Holland - Software Engineer building reliable systems and teams."

[params.author]
  name = "Garrett Holland"
  headline = "Software Engineer"
  bio = "Building reliable systems & teams."
  links = [
    { twitter = "https://twitter.com/skaterdurf" },
    { github = "https://github.com/glholland" },
    { linkedin = "https://linkedin.com/in/garrettholland" }
  ]
